apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: sysdig-agent
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      url: "http://172.21.220.146:7765/k8s_audit"
